### ISSUE TITLE
Consider adding long names to the `-e` and `-r` options

### ISSUE THREAD

**Issue by ngirard** [GarkGarcia/icon-pie#2]
This would make these options self-descriptive, and also would help users grasp their calls to your program after the fact (e.g. when revisiting their makefiles weeks or months after they wrote it).

**Comment by GarkGarcia** [comment]
I agree. What about `--entry` for `-e`? I'm also thinking about renaming `-r` to `-f` as of _filter_, so `-f` and `--filter`?

**Comment by ngirard** [comment]
Hey @GarkGarcia,

> I agree. What about `--entry` for `-e`?

Makes sense.

> I'm also thinking about renaming `-r` to `-f` as of _filter_, so `-f` and `--filter`?

Since we are talking about interpolation algorithms/techniques, I'd suggest `--interpolation`. `--filter` is too vague, IMHO.

Also, I'm not sure about the usefulness of the short variants (such as `-e`). Indeed, `icon-pie` is not meant to be called manually many times a day, like `ls` or `tar`, but is likely to be integrated as a command-line in a workflow, e.g. as a line in a `Makefile` file.

Such kind of commands benefit most from long options, because they convey the intent more clearly and make it easier to understand by another person, or by the one who wrote it months afterwards.

What do you think ?

**Comment by GarkGarcia** [comment]
Makes sense. I'd personally like to maintain the shorthand variants just because I know I'd use them a lot, but I don't mind deprecating them.

On regards to the likely scenario of `icon-pie` being integrated in a command-line workflow, maybe it's a good idea to provide support for a configuration file of sorts.

Like, the user could write a configuration file once and reference it in the command-line arguments instead of passing the configuration manually. Something like `yaml` seems reasonable.

However, I'd like to first sort out our support issues and then consider the addition of this feature.

**Comment by GarkGarcia** [comment]
@ngirard Also, what do you think about turning `-ico`, `-icns` and `png` into commands? So the syntax would look something like `$ icon-pie ico --entry icon.svg 32 64 -o output.ico`.

**Comment by GarkGarcia** [comment]
Integrated at _[release v0.1.0-alpha](https://github.com/GarkGarcia/icon-pie/releases/tag/v0.1.0-alpha)_.
